version: "3.7"
services:
  web:
    build:
      dockerfile: ./frontend/Dockerfile
      context: ./frontend
    links:
      - server:server
    ports:
      - 8080:80
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  server:
    build:
      dockerfile: ./Dockerfile
      context: .
    env_file:
      - .edhgo.env
    ports:
      - 8081:8080
    links:
      - postgres:postgres
    volumes:
      - "./persistence/migrations/:/app/persistence/migrations/"
    depends_on:
      - postgres
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  postgres:
    image: bitnami/postgresql:14
    volumes:
      - postgres-data:/bitnami/postgresql
    env_file:
      - ./.pg.env
    ports:
      - 5432:5432
volumes:
  postgres-data:
