version: "3.7"
services:
  web:
    image: dylanlott/edhgo-ui
    links:
      - server:server
    ports:
      - 8080:80
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  server:
    image: dylanlott/edhgo-server
    env_file:
      - .edhgo.env
    ports:
      - 8081:8080
    links:
      - redis:redis
      - postgres:postgres
    volumes:
      - "./persistence/migrations/:/app/persistence/migrations/"
    depends_on:
      - postgres
      - redis
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  redis:
    image: redis:latest
    volumes:
      - redis-data:/data
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
  postgres:
    image: bitnami/postgresql:14
    volumes:
      - postgres-data:/bitnami/postgresql
    env_file:
      - ./.pg.env
    ports:
      - 6375:5432
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 3
volumes:
  redis-data:
  postgres-data:
