version: "3.7"
services:
  web:
    image: openmtg/edhgo-ui:latest
    links:
      - server:server
    ports:
      - 8080:80
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  server:
    image: openmtg/edhgo-server:latest
    env_file:
      - .edhgo.env
    ports:
      - 8081:8080
    links:
      - postgres:postgres
    volumes:
      - "./persistence/migrations/:/app/persistence/migrations/"
    depends_on:
      - postgres
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  postgres:
    image: bitnami/postgresql:14.15.0
    volumes:
      - postgres-data:/bitnami/postgresql
    env_file:
      - ./.pg.env
    ports:
      - 6375:5432
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 3
volumes:
  postgres-data:
