version: "3.7"
services:
  web:
    image: dylanlott/edhgo-ui
    links:
      - server:server
    ports:
      - 8080:80
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - WATCHTOWER_POLL_INTERVAL=60
  server:
    image: dylanlott/edhgo-server
    env_file:
      - .edhgo.env
    ports:
      - 8081:8080
    links:
      - redis:redis
      - postgres:postgres
    depends_on:
      - postgres
      - redis
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  redis:
    image: redis:latest
    volumes:
      - redis-data:/data
  postgres:
    image: bitnami/postgresql
    volumes:
      - postgres-data:/bitnami/postgresql
    env_file:
      - ./.pg.env
  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 3
volumes:
  redis-data:
  postgres-data:
