version: "3.7"

services:
  web:
    build: frontend/Dockerfile
    links:
      - server:server
    ports:
      - 8081:80
  server:
    build: ./Dockerfile
    env_file:
      - .edhgo.env
    ports:
      - 8080:8080
    links:
      - redis:redis
      - postgres:postgres
  redis:
    image: redis:latest
    volumes:
      - redis-data:/data
    ports:
      - 6378:6379
  postgres:
    image: bitnami/postgresql
    volumes:
      - postgres-data:/bitnami/postgresql
    ports:
      - 5433:5432
    env_file:
      - ./.pg.env
volumes:
  redis-data:
  postgres-data:
