function statPanel({
  id,
  title,
  expr,
  gridPos,
  datasourceUid,
  unit = 'none',
  colorMode = 'value',
  thresholds = {
    mode: 'absolute',
    steps: [
      { color: 'red', value: null },
      { color: 'green', value: 1 },
    ],
  },
  mappings = [],
  description,
}) {
  return {
    id,
    type: 'stat',
    title,
    ...(description ? { description } : {}),
    datasource: { type: 'prometheus', uid: datasourceUid },
    gridPos,
    targets: [{ refId: 'A', expr }],
    options: {
      colorMode,
      graphMode: 'none',
      justifyMode: 'center',
      orientation: 'auto',
      reduceOptions: {
        calcs: ['lastNotNull'],
        fields: '',
        values: false,
      },
      textMode: 'auto',
    },
    fieldConfig: {
      defaults: {
        unit,
        thresholds,
        mappings,
      },
      overrides: [],
    },
  };
}

function timeSeriesPanel({
  id,
  title,
  targets,
  expr,
  gridPos,
  datasourceUid,
  unit = 'short',
  legendMode = 'list',
  min,
  thresholds,
  description,
}) {
  const defaults = { unit };
  if (min !== undefined) defaults.min = min;
  if (thresholds !== undefined) defaults.thresholds = thresholds;

  return {
    id,
    type: 'timeseries',
    title,
    ...(description ? { description } : {}),
    datasource: { type: 'prometheus', uid: datasourceUid },
    gridPos,
    targets: targets || [{ refId: 'A', expr, legendFormat: '__auto' }],
    options: {
      legend: {
        displayMode: legendMode,
        placement: 'bottom',
        showLegend: true,
      },
      tooltip: {
        mode: 'multi',
        sort: 'none',
      },
    },
    fieldConfig: {
      defaults,
      overrides: [],
    },
  };
}

function barGaugePanel({
  id,
  title,
  expr,
  gridPos,
  datasourceUid,
  unit = 'short',
  description,
  legendFormat,
}) {
  return {
    id,
    type: 'bargauge',
    title,
    ...(description ? { description } : {}),
    datasource: { type: 'prometheus', uid: datasourceUid },
    gridPos,
    targets: [{ refId: 'A', expr, ...(legendFormat ? { legendFormat } : {}) }],
    options: {
      displayMode: 'basic',
      orientation: 'horizontal',
      reduceOptions: {
        calcs: ['lastNotNull'],
        fields: '',
        values: false,
      },
      showUnfilled: true,
    },
    fieldConfig: {
      defaults: { unit },
      overrides: [],
    },
  };
}

function logsPanel({ id, title, expr, gridPos, logsDatasourceUid, description, options = {}, timeFrom }) {
  return {
    id,
    type: 'logs',
    title,
    ...(description ? { description } : {}),
    ...(timeFrom ? { timeFrom } : {}),
    datasource: { type: 'victoriametrics-logs-datasource', uid: logsDatasourceUid },
    gridPos,
    targets: [
      {
        refId: 'A',
        expr,
        queryType: 'instant',
        datasource: { type: 'victoriametrics-logs-datasource', uid: logsDatasourceUid },
      },
    ],
    options: {
      dedupStrategy: 'none',
      enableLogDetails: true,
      prettifyLogMessage: true,
      showCommonLabels: false,
      showLabels: false,
      showTime: true,
      sortOrder: 'Descending',
      wrapLogMessage: true,
      ...options,
    },
  };
}

function createArtistPilotAppDashboard({ datasourceUid, logsDatasourceUid }) {
  if (!datasourceUid) throw new Error('datasourceUid is required');
  if (!logsDatasourceUid) throw new Error('logsDatasourceUid is required');

  return {
    annotations: { list: [] },
    editable: true,
    fiscalYearStartMonth: 0,
    graphTooltip: 0,
    id: null,
    links: [],
    liveNow: false,
    panels: [
      statPanel({
        id: 1,
        title: 'Target Up',
        description: 'Whether the live artistpilot-api target is currently being scraped.',
        expr: 'up{job="artistpilot-api"}',
        gridPos: { h: 4, w: 4, x: 0, y: 0 },
        datasourceUid,
        mappings: [
          {
            type: 'value',
            options: {
              '0': { text: 'Down', color: 'red' },
              '1': { text: 'Up', color: 'green' },
            },
          },
        ],
      }),
      statPanel({
        id: 2,
        title: 'Monthly Active Users',
        description: 'Distinct users with an issued auth token in the last 30 days.',
        expr: 'max(artistpilot_monthly_active_users_total{job="artistpilot-api"})',
        gridPos: { h: 4, w: 4, x: 4, y: 0 },
        datasourceUid,
      }),
      statPanel({
        id: 3,
        title: 'Workspaces',
        description: 'Current total workspace count from the background refresh gauge.',
        expr: 'max(artistpilot_workspaces_total{job="artistpilot-api"})',
        gridPos: { h: 4, w: 4, x: 8, y: 0 },
        datasourceUid,
      }),
      statPanel({
        id: 4,
        title: 'User Base Since Deploy',
        description: 'Current registered-user count from the live ArtistPilot auth store.',
        expr: 'max(artistpilot_users_total{job="artistpilot-api"})',
        gridPos: { h: 4, w: 4, x: 12, y: 0 },
        datasourceUid,
      }),
      statPanel({
        id: 5,
        title: 'Active Subscriptions',
        description: 'Current count of active paid subscriptions across plans.',
        expr: 'sum(artistpilot_subscriptions_active{job="artistpilot-api"}) or vector(0)',
        gridPos: { h: 4, w: 4, x: 16, y: 0 },
        datasourceUid,
      }),
      statPanel({
        id: 6,
        title: 'Signup → Subscription Ratio',
        description: 'A simple paid-conversion proxy: current active subscriptions divided by tracked signups.',
        expr: '(100 * sum(artistpilot_subscriptions_active{job="artistpilot-api"}) / clamp_min(sum(artistpilot_signups_total{job="artistpilot-api"}), 1)) or vector(0)',
        gridPos: { h: 4, w: 4, x: 20, y: 0 },
        datasourceUid,
        unit: 'percent',
      }),
      statPanel({
        id: 7,
        title: 'Created Subscriptions Since Deploy',
        description: 'Total subscription create events observed since deploy.',
        expr: 'sum(artistpilot_subscriptions_total{job="artistpilot-api",event="created"}) or vector(0)',
        gridPos: { h: 4, w: 4, x: 0, y: 4 },
        datasourceUid,
      }),
      statPanel({
        id: 8,
        title: 'Cancelled Subscriptions Since Deploy',
        description: 'Total subscription cancellation events observed since deploy.',
        expr: 'sum(artistpilot_subscriptions_total{job="artistpilot-api",event="cancelled"}) or vector(0)',
        gridPos: { h: 4, w: 4, x: 4, y: 4 },
        datasourceUid,
      }),
      statPanel({
        id: 9,
        title: 'Subscription Events Since Deploy',
        description: 'Total subscription lifecycle events observed since deploy.',
        expr: 'sum(artistpilot_subscriptions_total{job="artistpilot-api"}) or vector(0)',
        gridPos: { h: 4, w: 4, x: 8, y: 4 },
        datasourceUid,
      }),
      statPanel({
        id: 10,
        title: 'Active SSE Connections',
        description: 'Currently open chat/event-stream connections.',
        expr: 'artistpilot_sse_connections_active{job="artistpilot-api"}',
        gridPos: { h: 4, w: 4, x: 12, y: 4 },
        datasourceUid,
      }),
      statPanel({
        id: 11,
        title: 'Chat Requests Since Deploy',
        description: 'Total streamed or completed chat requests across tenants and models.',
        expr: 'sum(artistpilot_chat_requests_total{job="artistpilot-api"})',
        gridPos: { h: 4, w: 4, x: 16, y: 4 },
        datasourceUid,
      }),
      statPanel({
        id: 12,
        title: 'Chat Success Rate',
        description: 'Secondary product-health signal: share of tracked chat requests that finished successfully.',
        expr: '100 * sum(artistpilot_chat_requests_total{job="artistpilot-api",status="success"}) / clamp_min(sum(artistpilot_chat_requests_total{job="artistpilot-api"}), 1)',
        gridPos: { h: 4, w: 4, x: 20, y: 4 },
        datasourceUid,
        unit: 'percent',
      }),
      barGaugePanel({
        id: 13,
        title: 'Signups by Plan & Source',
        description: 'Cumulative signup mix across the tracked plan and source labels.',
        expr: 'sum by (plan,source) (artistpilot_signups_total{job="artistpilot-api"})',
        gridPos: { h: 8, w: 8, x: 0, y: 8 },
        datasourceUid,
        legendFormat: '{{plan}} • {{source}}',
      }),
      barGaugePanel({
        id: 14,
        title: 'Active Subscriptions by Plan',
        description: 'Current active paid subscriptions by plan.',
        expr: 'sum by (plan) (artistpilot_subscriptions_active{job="artistpilot-api"})',
        gridPos: { h: 8, w: 8, x: 8, y: 8 },
        datasourceUid,
        legendFormat: '{{plan}}',
      }),
      barGaugePanel({
        id: 15,
        title: 'Subscription Lifecycle Events by Plan & Event',
        description: 'Cumulative subscription lifecycle mix across plan and event labels.',
        expr: 'sum by (plan,event) (artistpilot_subscriptions_total{job="artistpilot-api"})',
        gridPos: { h: 8, w: 8, x: 16, y: 8 },
        datasourceUid,
        legendFormat: '{{plan}} • {{event}}',
      }),
      barGaugePanel({
        id: 16,
        title: 'Subscription Event Mix Since Deploy',
        description: 'Overall subscription lifecycle event mix, independent of plan.',
        expr: 'sum by (event) (artistpilot_subscriptions_total{job="artistpilot-api"})',
        gridPos: { h: 8, w: 8, x: 0, y: 16 },
        datasourceUid,
        legendFormat: '{{event}}',
      }),
      timeSeriesPanel({
        id: 17,
        title: 'Signup Rate by Plan & Source',
        description: 'Rate of new signups, split by acquisition/source labels so funnel shifts are visible quickly.',
        expr: 'sum by (plan,source) (rate(artistpilot_signups_total{job="artistpilot-api"}[$__rate_interval]))',
        gridPos: { h: 8, w: 16, x: 8, y: 16 },
        datasourceUid,
        unit: 'reqps',
      }),
      timeSeriesPanel({
        id: 18,
        title: 'Subscription Event Rate by Plan & Event',
        description: 'Rate of subscription lifecycle changes, split by plan and lifecycle event.',
        expr: 'sum by (plan,event) (rate(artistpilot_subscriptions_total{job="artistpilot-api"}[$__rate_interval]))',
        gridPos: { h: 8, w: 12, x: 0, y: 24 },
        datasourceUid,
        unit: 'reqps',
      }),
      timeSeriesPanel({
        id: 19,
        title: 'Signups vs Active Subscriptions',
        description: 'Overlay of cumulative signups against current active subscriptions as a simple funnel health read.',
        targets: [
          {
            refId: 'A',
            expr: 'sum(artistpilot_signups_total{job="artistpilot-api"})',
            legendFormat: 'signups',
          },
          {
            refId: 'B',
            expr: 'sum(artistpilot_subscriptions_active{job="artistpilot-api"})',
            legendFormat: 'active subscriptions',
          },
        ],
        gridPos: { h: 8, w: 12, x: 12, y: 24 },
        datasourceUid,
      }),
      barGaugePanel({
        id: 20,
        title: 'HTTP Status Mix Since Deploy',
        description: 'Cumulative request mix by status; useful for spotting whether failures are isolated or systemic.',
        expr: 'sum by (status) (artistpilot_http_requests_total{job="artistpilot-api"})',
        gridPos: { h: 8, w: 8, x: 0, y: 32 },
        datasourceUid,
        legendFormat: '{{status}}',
      }),
      barGaugePanel({
        id: 21,
        title: 'Errors by Kind',
        description: 'Application error counter split by the emitted kind label.',
        expr: 'sum by (kind) (artistpilot_errors_total{job="artistpilot-api"})',
        gridPos: { h: 8, w: 8, x: 8, y: 32 },
        datasourceUid,
        legendFormat: '{{kind}}',
      }),
      timeSeriesPanel({
        id: 22,
        title: 'Request Rate by Status',
        description: 'Live request pressure split by status so you can correlate spikes with the funnel panels above.',
        expr: 'sum by (status) (rate(artistpilot_http_requests_total{job="artistpilot-api"}[$__rate_interval]))',
        gridPos: { h: 8, w: 8, x: 16, y: 32 },
        datasourceUid,
        unit: 'reqps',
        min: 0,
      }),
      statPanel({
        id: 23,
        title: 'Resident Memory',
        description: 'Process RSS from the live scrape target for fast triage when the app feels unhealthy.',
        expr: 'process_resident_memory_bytes{job="artistpilot-api"}',
        gridPos: { h: 8, w: 6, x: 0, y: 40 },
        datasourceUid,
        unit: 'bytes',
      }),
      timeSeriesPanel({
        id: 24,
        title: 'Process CPU Usage',
        description: 'Live CPU usage from the app process so request spikes and log spikes can be correlated quickly.',
        expr: '100 * rate(process_cpu_seconds_total{job="artistpilot-api"}[$__rate_interval])',
        gridPos: { h: 8, w: 8, x: 6, y: 40 },
        datasourceUid,
        unit: 'percent',
        min: 0,
      }),
      logsPanel({
        id: 25,
        title: 'API/Web stderr & deploy churn',
        description: 'The sharpest operational log slice: stderr output and deploy/startup churn from ArtistPilot API and web containers.',
        expr: '(label.com.dokku.app-name:=artistpilot-api OR label.com.dokku.app-name:=artistpilot-web) stream:=stderr',
        gridPos: { h: 10, w: 8, x: 0, y: 48 },
        logsDatasourceUid,
        timeFrom: '24h',
      }),
      logsPanel({
        id: 26,
        title: '4xx/5xx Request Lines',
        description: 'Request logs biased toward failure responses so auth, signup, and checkout edges are easier to spot without swimming through all traffic.',
        expr: 'label.com.dokku.app-name:=artistpilot-api message:~"request" message:~"status.:4..|status.:5.."',
        gridPos: { h: 10, w: 8, x: 8, y: 48 },
        logsDatasourceUid,
        timeFrom: '24h',
      }),
      logsPanel({
        id: 27,
        title: 'Signup & Billing Events',
        description: 'High-signal business flow events for signup verification and Stripe/webhook handling.',
        expr: 'label.com.dokku.app-name:=artistpilot-api ("signup verification code generated" OR "stripe webhook processed")',
        gridPos: { h: 10, w: 8, x: 16, y: 48 },
        logsDatasourceUid,
        timeFrom: '7d',
      }),
      statPanel({
        id: 28,
        title: 'New Users Last 24h',
        description: 'Recent tracked signups across all plans and landing sources.',
        expr: 'sum(increase(artistpilot_signups_total{job="artistpilot-api"}[24h])) or vector(0)',
        gridPos: { h: 8, w: 10, x: 14, y: 40 },
        datasourceUid,
      }),
      statPanel({
        id: 29,
        title: 'Daily Active Users',
        description: 'Distinct users with an issued auth token in the last 24 hours.',
        expr: 'max(artistpilot_daily_active_users_total{job="artistpilot-api"})',
        gridPos: { h: 8, w: 7, x: 0, y: 40 },
        datasourceUid,
      }),
      statPanel({
        id: 30,
        title: 'Weekly Active Users',
        description: 'Distinct users with an issued auth token in the last 7 days.',
        expr: 'max(artistpilot_weekly_active_users_total{job="artistpilot-api"})',
        gridPos: { h: 8, w: 7, x: 7, y: 40 },
        datasourceUid,
      }),
    ],
    refresh: '30s',
    schemaVersion: 41,
    tags: ['artistpilot', 'app', 'engagement', 'signups', 'subscriptions'],
    templating: { list: [] },
    time: { from: 'now-24h', to: 'now' },
    timepicker: {},
    timezone: 'browser',
    title: 'ArtistPilot App Overview',
    uid: 'artistpilot-app-overview',
    version: 7,
    weekStart: '',
  };
}

module.exports = {
  createArtistPilotAppDashboard,
};
