function statPanel({
  id,
  title,
  expr,
  gridPos,
  datasourceUid,
  unit = 'none',
  colorMode = 'value',
  thresholds = {
    mode: 'absolute',
    steps: [
      { color: 'red', value: null },
      { color: 'green', value: 1 },
    ],
  },
  mappings = [],
  description,
}) {
  return {
    id,
    type: 'stat',
    title,
    ...(description ? { description } : {}),
    datasource: { type: 'prometheus', uid: datasourceUid },
    gridPos,
    targets: [{ refId: 'A', expr }],
    options: {
      colorMode,
      graphMode: 'none',
      justifyMode: 'center',
      orientation: 'auto',
      reduceOptions: {
        calcs: ['lastNotNull'],
        fields: '',
        values: false,
      },
      textMode: 'auto',
    },
    fieldConfig: {
      defaults: {
        unit,
        thresholds,
        mappings,
      },
      overrides: [],
    },
  };
}

function timeSeriesPanel({
  id,
  title,
  targets,
  expr,
  gridPos,
  datasourceUid,
  unit = 'short',
  legendMode = 'list',
  min,
  thresholds,
  description,
}) {
  const defaults = { unit };
  if (min !== undefined) defaults.min = min;
  if (thresholds !== undefined) defaults.thresholds = thresholds;

  return {
    id,
    type: 'timeseries',
    title,
    ...(description ? { description } : {}),
    datasource: { type: 'prometheus', uid: datasourceUid },
    gridPos,
    targets: targets || [{ refId: 'A', expr, legendFormat: '__auto' }],
    options: {
      legend: {
        displayMode: legendMode,
        placement: 'bottom',
        showLegend: true,
      },
      tooltip: {
        mode: 'multi',
        sort: 'none',
      },
    },
    fieldConfig: {
      defaults,
      overrides: [],
    },
  };
}

function barGaugePanel({
  id,
  title,
  expr,
  gridPos,
  datasourceUid,
  unit = 'short',
  description,
  legendFormat = '{{route}}',
}) {
  return {
    id,
    type: 'bargauge',
    title,
    ...(description ? { description } : {}),
    datasource: { type: 'prometheus', uid: datasourceUid },
    gridPos,
    targets: [{ refId: 'A', expr, legendFormat }],
    options: {
      displayMode: 'basic',
      orientation: 'horizontal',
      reduceOptions: {
        calcs: ['lastNotNull'],
        fields: '',
        values: false,
      },
      showUnfilled: true,
    },
    fieldConfig: {
      defaults: { unit },
      overrides: [],
    },
  };
}

function createJankAppDashboard({ datasourceUid }) {
  if (!datasourceUid) throw new Error('datasourceUid is required');

  return {
    annotations: { list: [] },
    editable: true,
    fiscalYearStartMonth: 0,
    graphTooltip: 0,
    id: null,
    links: [],
    liveNow: false,
    panels: [
      statPanel({
        id: 1,
        title: 'Target Up',
        description: 'Whether the live jank-app target is currently being scraped.',
        expr: 'up{job="jank-app"}',
        gridPos: { h: 4, w: 4, x: 0, y: 0 },
        datasourceUid,
        mappings: [
          {
            type: 'value',
            options: {
              '0': { text: 'Down', color: 'red' },
              '1': { text: 'Up', color: 'green' },
            },
          },
        ],
      }),
      statPanel({
        id: 2,
        title: 'Searches Last 24h',
        description: 'Recent search demand across the forum, regardless of outcome.',
        expr: 'sum(increase(jank_search_queries_total{job="jank-app"}[24h])) or vector(0)',
        gridPos: { h: 4, w: 4, x: 4, y: 0 },
        datasourceUid,
      }),
      statPanel({
        id: 3,
        title: 'New Users Last 24h',
        description: 'Recent successful account creations across Jank auth surfaces.',
        expr: 'sum(increase(jank_signup_attempts_total{job="jank-app",result="success"}[24h])) or vector(0)',
        gridPos: { h: 4, w: 4, x: 8, y: 0 },
        datasourceUid,
      }),
      statPanel({
        id: 4,
        title: 'Daily Active Users',
        description: 'Distinct users with persisted authenticated activity in the last 24 hours.',
        expr: 'max(jank_daily_active_users_total{job="jank-app"})',
        gridPos: { h: 4, w: 4, x: 12, y: 0 },
        datasourceUid,
      }),
      statPanel({
        id: 5,
        title: 'Threads Created Last 24h',
        description: 'Recent forum thread creation volume.',
        expr: 'sum(increase(jank_threads_created_total{job="jank-app"}[24h])) or vector(0)',
        gridPos: { h: 4, w: 4, x: 16, y: 0 },
        datasourceUid,
      }),
      statPanel({
        id: 6,
        title: 'Posts Created Last 24h',
        description: 'Recent forum replies/posts created by users.',
        expr: 'sum(increase(jank_posts_created_total{job="jank-app"}[24h])) or vector(0)',
        gridPos: { h: 4, w: 4, x: 20, y: 0 },
        datasourceUid,
      }),
      statPanel({
        id: 7,
        title: 'Search Empty Share',
        description: 'Share of recent searches that returned nothing useful.',
        expr: '100 * sum(increase(jank_search_queries_total{job="jank-app",result="empty"}[24h])) / clamp_min(sum(increase(jank_search_queries_total{job="jank-app"}[24h])), 1)',
        gridPos: { h: 4, w: 4, x: 0, y: 4 },
        datasourceUid,
        unit: 'percent',
        thresholds: {
          mode: 'absolute',
          steps: [
            { color: 'green', value: null },
            { color: 'yellow', value: 25 },
            { color: 'red', value: 50 },
          ],
        },
      }),
      statPanel({
        id: 8,
        title: 'Signup Success Rate',
        description: 'Quality read on the signup funnel over the last 24 hours.',
        expr: '100 * sum(increase(jank_signup_attempts_total{job="jank-app",result="success"}[24h])) / clamp_min(sum(increase(jank_signup_attempts_total{job="jank-app"}[24h])), 1)',
        gridPos: { h: 4, w: 4, x: 4, y: 4 },
        datasourceUid,
        unit: 'percent',
      }),
      statPanel({
        id: 9,
        title: 'Login Success Rate',
        description: 'Quality read on whether people who try to come back are getting in.',
        expr: '100 * sum(increase(jank_login_attempts_total{job="jank-app",result="success"}[24h])) / clamp_min(sum(increase(jank_login_attempts_total{job="jank-app"}[24h])), 1)',
        gridPos: { h: 4, w: 4, x: 8, y: 4 },
        datasourceUid,
        unit: 'percent',
      }),
      statPanel({
        id: 10,
        title: 'Contribution Depth',
        description: 'Average posts created per newly created thread in the last 24 hours.',
        expr: '(sum(increase(jank_posts_created_total{job="jank-app"}[24h])) / clamp_min(sum(increase(jank_threads_created_total{job="jank-app"}[24h])), 1)) or vector(0)',
        gridPos: { h: 4, w: 4, x: 12, y: 4 },
        datasourceUid,
      }),
      statPanel({
        id: 11,
        title: 'Card Trees Created Last 24h',
        description: 'Recent card-tree creation volume across tracked scopes.',
        expr: 'sum(increase(jank_card_trees_created_total{job="jank-app"}[24h])) or vector(0)',
        gridPos: { h: 4, w: 4, x: 16, y: 4 },
        datasourceUid,
      }),
      statPanel({
        id: 12,
        title: 'Search → Thread Yield',
        description: 'Simple product-yield proxy: recent thread creation divided by matched searches.',
        expr: '100 * sum(increase(jank_threads_created_total{job="jank-app"}[24h])) / clamp_min(sum(increase(jank_search_queries_total{job="jank-app",result="match"}[24h])), 1)',
        gridPos: { h: 4, w: 4, x: 20, y: 4 },
        datasourceUid,
        unit: 'percent',
      }),
      barGaugePanel({
        id: 13,
        title: 'Search Outcomes Last 24h',
        description: 'Search demand split by outcome so empty-result drift is easy to spot.',
        expr: 'sum by (result) (increase(jank_search_queries_total{job="jank-app"}[24h]))',
        gridPos: { h: 8, w: 8, x: 0, y: 8 },
        datasourceUid,
        legendFormat: '{{result}}',
      }),
      barGaugePanel({
        id: 14,
        title: 'Login Outcomes Last 24h',
        description: 'Login attempts grouped by auth surface and outcome.',
        expr: 'sum by (surface,result) (increase(jank_login_attempts_total{job="jank-app"}[24h]))',
        gridPos: { h: 8, w: 8, x: 8, y: 8 },
        datasourceUid,
        legendFormat: '{{surface}} • {{result}}',
      }),
      barGaugePanel({
        id: 15,
        title: 'Signup Outcomes Last 24h',
        description: 'Signup attempts grouped by auth surface and outcome.',
        expr: 'sum by (surface,result) (increase(jank_signup_attempts_total{job="jank-app"}[24h]))',
        gridPos: { h: 8, w: 8, x: 16, y: 8 },
        datasourceUid,
        legendFormat: '{{surface}} • {{result}}',
      }),
      timeSeriesPanel({
        id: 16,
        title: 'Creation Activity (6h rolling)',
        description: 'Recent creation behavior across threads, posts, and card trees.',
        targets: [
          { refId: 'A', expr: 'sum(increase(jank_threads_created_total{job="jank-app"}[6h]))', legendFormat: 'threads' },
          { refId: 'B', expr: 'sum(increase(jank_posts_created_total{job="jank-app"}[6h]))', legendFormat: 'posts' },
          { refId: 'C', expr: 'sum(increase(jank_card_trees_created_total{job="jank-app"}[6h]))', legendFormat: 'card trees' },
        ],
        gridPos: { h: 8, w: 8, x: 0, y: 16 },
        datasourceUid,
      }),
      timeSeriesPanel({
        id: 17,
        title: 'Funnel Activity (6h rolling)',
        description: 'Recent discovery → auth → contribution movement in one view.',
        targets: [
          { refId: 'A', expr: 'sum(increase(jank_search_queries_total{job="jank-app",result="match"}[6h]))', legendFormat: 'search matches' },
          { refId: 'B', expr: 'sum(increase(jank_signup_attempts_total{job="jank-app",result="success"}[6h]))', legendFormat: 'successful signups' },
          { refId: 'C', expr: 'sum(increase(jank_login_attempts_total{job="jank-app",result="success"}[6h]))', legendFormat: 'successful logins' },
          { refId: 'D', expr: 'sum(increase(jank_threads_created_total{job="jank-app"}[6h]))', legendFormat: 'threads created' },
        ],
        gridPos: { h: 8, w: 8, x: 8, y: 16 },
        datasourceUid,
      }),
      timeSeriesPanel({
        id: 18,
        title: 'Route Demand (6h rolling)',
        description: 'Low-traffic-friendly view of recent demand across the key public routes.',
        expr: 'sum by (route) (increase(jank_http_requests_total{job="jank-app",route=~"/|/login|/search",route!="/metrics"}[6h]))',
        gridPos: { h: 8, w: 8, x: 16, y: 16 },
        datasourceUid,
      }),
      timeSeriesPanel({
        id: 19,
        title: 'Request Rate by Route',
        description: '1h-smoothed request rate by route so low-traffic forum behavior still shows up clearly.',
        expr: 'sum by (route,status_code) (rate(jank_http_requests_total{job="jank-app",route!="/metrics"}[1h]))',
        gridPos: { h: 8, w: 12, x: 0, y: 24 },
        datasourceUid,
        unit: 'reqps',
      }),
      timeSeriesPanel({
        id: 20,
        title: 'P95 Request Latency by Route',
        description: '1h-smoothed p95 latency by route to keep sparse traffic visible in early production.',
        expr: '1000 * histogram_quantile(0.95, sum by (le,route) (rate(jank_http_request_duration_seconds_bucket{job="jank-app",route!="/metrics"}[1h])))',
        gridPos: { h: 8, w: 12, x: 12, y: 24 },
        datasourceUid,
        unit: 'ms',
        min: 0,
      }),
      statPanel({
        id: 21,
        title: 'Resident Memory',
        expr: 'process_resident_memory_bytes{job="jank-app"}',
        gridPos: { h: 8, w: 8, x: 8, y: 32 },
        datasourceUid,
        unit: 'bytes',
      }),
      timeSeriesPanel({
        id: 22,
        title: 'Process CPU Usage',
        expr: '100 * rate(process_cpu_seconds_total{job="jank-app"}[$__rate_interval])',
        gridPos: { h: 8, w: 8, x: 16, y: 32 },
        datasourceUid,
        unit: 'percent',
        min: 0,
      }),
      statPanel({
        id: 23,
        title: 'User Base Since Deploy',
        description: 'Current registered-user count from persisted Jank auth state.',
        expr: 'max(jank_users_total{job="jank-app"})',
        gridPos: { h: 8, w: 8, x: 0, y: 32 },
        datasourceUid,
      }),
      statPanel({
        id: 24,
        title: 'Weekly Active Users',
        description: 'Distinct users with persisted authenticated activity in the last 7 days.',
        expr: 'max(jank_weekly_active_users_total{job="jank-app"})',
        gridPos: { h: 8, w: 8, x: 8, y: 40 },
        datasourceUid,
      }),
      statPanel({
        id: 25,
        title: 'Monthly Active Users',
        description: 'Distinct users with persisted authenticated activity in the last 30 days.',
        expr: 'max(jank_monthly_active_users_total{job="jank-app"})',
        gridPos: { h: 8, w: 8, x: 16, y: 40 },
        datasourceUid,
      }),
    ],
    refresh: '30s',
    schemaVersion: 41,
    tags: ['jank', 'app', 'engagement', 'business-metrics'],
    templating: { list: [] },
    time: { from: 'now-24h', to: 'now' },
    timepicker: {},
    timezone: 'browser',
    title: 'Jank App Overview',
    uid: 'jank-app-overview',
    version: 2,
    weekStart: '',
  };
}

module.exports = {
  createJankAppDashboard,
};
