// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package server

import (
	"time"
)

type BoardState struct {
	User       *User   `json:"User"`
	Commander  []*Card `json:"Commander"`
	Library    []*Card `json:"Library"`
	Graveyard  []*Card `json:"Graveyard"`
	Exiled     []*Card `json:"Exiled"`
	Field      []*Card `json:"Field"`
	Hand       []*Card `json:"Hand"`
	Revealed   []*Card `json:"Revealed"`
	Controlled []*Card `json:"Controlled"`
}

type Card struct {
	Name string `json:"Name"`
	ID   string `json:"ID"`
}

type Deck struct {
	Commander string   `json:"Commander"`
	Library   []string `json:"Library"`
}

type Game struct {
	ID      string  `json:"id"`
	Players []*User `json:"players"`
}

type InputBoardState struct {
	UserID     string   `json:"UserID"`
	Commander  []string `json:"Commander"`
	Library    []string `json:"Library"`
	Graveyard  []string `json:"Graveyard"`
	Exiled     []string `json:"Exiled"`
	Field      []string `json:"Field"`
	Hand       []string `json:"Hand"`
	Revealed   []string `json:"Revealed"`
	Controlled []string `json:"Controlled"`
	Counters   []string `json:"Counters"`
	Meta       []string `json:"Meta"`
}

type InputDeck struct {
	Cards []string `json:"cards"`
}

type InputGame struct {
	Players []*InputUser `json:"players"`
}

type InputSignup struct {
	Username string `json:"Username"`
	Email    string `json:"Email"`
	Password string `json:"Password"`
}

type InputUser struct {
	Deck     string `json:"Deck"`
	Username string `json:"Username"`
}

type Message struct {
	ID        string    `json:"id"`
	User      string    `json:"user"`
	CreatedAt time.Time `json:"createdAt"`
	Text      string    `json:"text"`
}

type User struct {
	ID         string      `json:"id"`
	Username   string      `json:"username"`
	Deck       string      `json:"deck"`
	Boardstate *BoardState `json:"boardstate"`
}
