package server

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"
)

// Signup is the resolver for the signup field.
func (r *mutationResolver) Signup(ctx context.Context, username string, password string) (*User, error) {
	panic(fmt.Errorf("not implemented: Signup - signup"))
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, username string, password string) (*User, error) {
	panic(fmt.Errorf("not implemented: Login - login"))
}

// CreateGame is the resolver for the createGame field.
func (r *mutationResolver) CreateGame(ctx context.Context, input InputCreateGame) (*Game, error) {
	panic(fmt.Errorf("not implemented: CreateGame - createGame"))
}

// JoinGame is the resolver for the joinGame field.
func (r *mutationResolver) JoinGame(ctx context.Context, input *InputJoinGame) (*Game, error) {
	panic(fmt.Errorf("not implemented: JoinGame - joinGame"))
}

// UpdateGame is the resolver for the updateGame field.
func (r *mutationResolver) UpdateGame(ctx context.Context, input InputGame) (*Game, error) {
	panic(fmt.Errorf("not implemented: UpdateGame - updateGame"))
}

// PassPriority is the resolver for the passPriority field.
func (r *mutationResolver) PassPriority(ctx context.Context, gameID string, toPlayer string) (*Game, error) {
	panic(fmt.Errorf("not implemented: PassPriority - passPriority"))
}

// AdvancePhase is the resolver for the advancePhase field.
func (r *mutationResolver) AdvancePhase(ctx context.Context, gameID string, phase string, number *int) (*Game, error) {
	panic(fmt.Errorf("not implemented: AdvancePhase - advancePhase"))
}

// UpdateBoardState is the resolver for the updateBoardState field.
func (r *mutationResolver) UpdateBoardState(ctx context.Context, input InputBoardState) (*BoardState, error) {
	panic(fmt.Errorf("not implemented: UpdateBoardState - updateBoardState"))
}

// ClaimWin is the resolver for the claimWin field.
func (r *mutationResolver) ClaimWin(ctx context.Context, gameID string, condition *string) (*Game, error) {
	panic(fmt.Errorf("not implemented: ClaimWin - claimWin"))
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, userID *string) ([]string, error) {
	panic(fmt.Errorf("not implemented: Users - users"))
}

// Games is the resolver for the games field.
func (r *queryResolver) Games(ctx context.Context, offset int, limit int) ([]*Game, error) {
	panic(fmt.Errorf("not implemented: Games - games"))
}

// GetGame is the resolver for the getGame field.
func (r *queryResolver) GetGame(ctx context.Context, gameID string) (*Game, error) {
	panic(fmt.Errorf("not implemented: GetGame - getGame"))
}

// GameLogs is the resolver for the gameLogs field.
func (r *queryResolver) GameLogs(ctx context.Context, gameID string, offset int, limit int) ([]*GameLogEvent, error) {
	panic(fmt.Errorf("not implemented: GameLogs - gameLogs"))
}

// Card is the resolver for the card field.
func (r *queryResolver) Card(ctx context.Context, name string, id *string) (*Card, error) {
	panic(fmt.Errorf("not implemented: Card - card"))
}

// Cards is the resolver for the cards field.
func (r *queryResolver) Cards(ctx context.Context, list []string) ([]*Card, error) {
	panic(fmt.Errorf("not implemented: Cards - cards"))
}

// Search is the resolver for the search field.
func (r *queryResolver) Search(ctx context.Context, name *string, colors []*string, colorIdentity []*string, keywords []*string) ([]*Card, error) {
	panic(fmt.Errorf("not implemented: Search - search"))
}

// SearchAll is the resolver for the searchAll field.
func (r *queryResolver) SearchAll(ctx context.Context, name *string, colors []*string, colorIdentity []*string, keywords []*string) ([]*Card, error) {
	panic(fmt.Errorf("not implemented: SearchAll - searchAll"))
}

// GameUpdated is the resolver for the gameUpdated field.
func (r *subscriptionResolver) GameUpdated(ctx context.Context, gameID string, userID string) (<-chan *Game, error) {
	panic(fmt.Errorf("not implemented: GameUpdated - gameUpdated"))
}

// BoardstateUpdated is the resolver for the boardstateUpdated field.
func (r *subscriptionResolver) BoardstateUpdated(ctx context.Context, obsID string, userID string) (<-chan *BoardState, error) {
	panic(fmt.Errorf("not implemented: BoardstateUpdated - boardstateUpdated"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
