CREATE TABLE IF NOT EXISTS cards (
    ID TEXT PRIMARY KEY NOT NULL,
    Artist TEXT,
    AsciiName TEXT,
    Availability TEXT,
    BorderColor TEXT,
    CardKingdomId TEXT,
    ColorIdentity TEXT,
    ColorIndicator TEXT,
    Colors TEXT,
    ConvertedManaCost TEXT,
    FaceConvertedManaCost TEXT,
    FaceManaValue TEXT,
    FlavorName TEXT,
    FlavorText TEXT,
    Keywords TEXT,
    MTGJSONV4ID TEXT,
    Name TEXT,
    Number TEXT,
    OriginalText TEXT,
    OriginalType TEXT,
    Power TEXT,
    ScryfallID TEXT,
    ScryfallIllustrationID TEXT,
    ScryfallOracleID TEXT,
    SetCode TEXT,
    Side TEXT,
    Subtypes TEXT,
    Supertypes TEXT,
    TCGPlayerProductID TEXT,
    Text TEXT,
    Toughness TEXT,
    Type TEXT,
    Types TEXT,
    UUID TEXT NOT NULL UNIQUE
);